services:
  orders-db:
    image: postgres:17
    container_name: orders-db-postgres
    env_file:
      - order-service/.env
    ports:
      - "5432:5432"
    volumes:
      - orders-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dima_terekhov -d orders_db" ]
      interval: 20s
      timeout: 5s
      retries: 15
      start_period: 10s

  orders-db-migrate:
    image: migrate/migrate
    volumes:
      - ./order-service/internal/infrastructure/db/postgres/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://dima_terekhov:lowkey_tough@orders-db:5432/orders_db?sslmode=disable",
      "up"
    ]
    depends_on:
      orders-db:
        condition: service_healthy

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_started
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Add host for local debug
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server kafka:9092 --list > /dev/null" ]
      interval: 20s
      timeout: 30s
      retries: 20

  kafka-init:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-init
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: [ "sh", "-c" ]
    command: |
      "
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic order-command-events --partitions 1 --replication-factor 1
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic payment-events --partitions 1 --replication-factor 1
      "
    restart: "no"

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    env_file:
      - order-service/.env
    ports:
      - "8080:8080"
    depends_on:
      orders-db:
        condition: service_healthy
      orders-db-migrate:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully

  payments-db:
    image: postgres:17
    container_name: payments-db-postgres
    env_file:
      - payment-service/.env
    ports:
      - "5433:5432"
    volumes:
      - payments-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U vlad_bukharin -d payments_db" ]
      interval: 20s
      timeout: 5s
      retries: 15
      start_period: 10s

  payments-db-migrate:
    image: migrate/migrate
    volumes:
      - ./payment-service/internal/infrastructure/db/postgres/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://vlad_bukharin:lowkey_tough@payments-db:5432/payments_db?sslmode=disable",
      "up"
    ]
    depends_on:
      payments-db:
        condition: service_healthy

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    env_file:
      - payment-service/.env
    ports:
      - "8088:8080"
    depends_on:
      payments-db:
        condition: service_healthy
      payments-db-migrate:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully

  api-gateway:
    build:
      context: api-gateway/
    container_name: api-gateway
    ports:
      - "80:80"
    depends_on:
      - order-service
      - payment-service

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9093:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

volumes:
  orders-db-data:
  payments-db-data: